### ISSUE TITLE
httpConsole error

### ISSUE THREAD

**Issue by donbarton639** [Sorroko/HTTPConsole#5]
i use command save-all, and get erorr in my log.
2013-02-12 20:00:01 [INFO] [34;1m[all] Autosaving world...[m
2013-02-12 20:00:01 [INFO] CONSOLE: Forcing save..[m
2013-02-12 20:00:01 [SEVERE] java.util.ConcurrentModificationException
2013-02-12 20:00:01 [SEVERE]    at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1115)
2013-02-12 20:00:01 [SEVERE]    at java.util.TreeMap$KeyIterator.next(TreeMap.java:1169)
2013-02-12 20:00:01 [SEVERE]    at net.minecraft.server.v1_4_R1.WorldServer.a(WorldServer.java:518)
2013-02-12 20:00:01 [SEVERE]    at net.minecraft.server.v1_4_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:261)
2013-02-12 20:00:01 [SEVERE]    at net.minecraft.server.v1_4_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:126)
2013-02-12 20:00:01 [SEVERE]    at net.minecraft.server.v1_4_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:208)
2013-02-12 20:00:01 [SEVERE]    at net.minecraft.server.v1_4_R1.ChunkProviderServer.saveChunks(ChunkProviderServer.java:265)
2013-02-12 20:00:01 [SEVERE]    at net.minecraft.server.v1_4_R1.WorldServer.save(WorldServer.java:709)
2013-02-12 20:00:01 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.save(CraftWorld.java:648)
2013-02-12 20:00:01 [SEVERE]    at org.bukkit.command.defaults.SaveCommand.execute(SaveCommand.java:30)
2013-02-12 20:00:01 [SEVERE]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
2013-02-12 20:00:01 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
2013-02-12 20:00:01 [SEVERE]    at org.theanticookie.bukkit.httpconsole.RequestHandler.executeConsoleCommand(RequestHandler.java:86)
2013-02-12 20:00:01 [SEVERE]    at org.theanticookie.bukkit.httpconsole.RequestHandler.HandleRequest(RequestHandler.java:130)
2013-02-12 20:00:01 [SEVERE]    at org.theanticookie.bukkit.httpconsole.HTTPServer.requestHandler(HTTPServer.java:139)
2013-02-12 20:00:01 [SEVERE]    at org.theanticookie.bukkit.httpconsole.HTTPServer.run(HTTPServer.java:335)
2013-02-12 20:00:01 [SEVERE] HTTPConsole: An HTTP request handler failed
2013-02-12 20:00:01 [SEVERE] Unhandled exception executing 'save-all' in org.bukkit.command.defaults.SaveCommand(save-all)
org.bukkit.command.CommandException: Unhandled exception executing 'save-all' in org.bukkit.command.defaults.SaveCommand(save-all)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:190)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
    at org.theanticookie.bukkit.httpconsole.RequestHandler.executeConsoleCommand(RequestHandler.java:86)
    at org.theanticookie.bukkit.httpconsole.RequestHandler.HandleRequest(RequestHandler.java:130)
    at org.theanticookie.bukkit.httpconsole.HTTPServer.requestHandler(HTTPServer.java:139)
    at org.theanticookie.bukkit.httpconsole.HTTPServer.run(HTTPServer.java:335)
Caused by: java.util.ConcurrentModificationException
    at org.bukkit.craftbukkit.v1_4_R1.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:299)
    at net.minecraft.server.v1_4_R1.ChunkProviderServer.saveChunks(ChunkProviderServer.java:257)
    at net.minecraft.server.v1_4_R1.WorldServer.save(WorldServer.java:709)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.save(CraftWorld.java:648)
    at org.bukkit.command.defaults.SaveCommand.execute(SaveCommand.java:30)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
    ... 5 more
2013-02-12 20:00:01 [INFO] [34;1m[all] Autosaving complete![m

**Comment by Sorroko** [comment]
This is a known error however it does not affect commands (as far as I know) and it's not easily solvable due to bukkits structure.
Technical details: The plugins runs an async HTTP server which executes commands from it's async thread causing issues with commands that expect to be run synchronously.
Small chance this might be fixed in the next release.
